apiVersion: apps/v1
kind: Deployment
metadata:
  name: accommodation-ti
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accommodation-ti
  template:
    metadata:
      labels:
        app: accommodation-ti
    spec:
      containers:
        - name: springboot-container
          image: ${DOCKER_IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL_PROD
              valueFrom:
                configMapKeyRef:
                  name: accommodation-ti-config
                  key: DATABASE_URL_PROD
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: accommodation-ti-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accommodation-ti-secret
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: accommodation-ti-secret
                  key: JWT_SECRET_KEY
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: accommodation-ti-secret
                  key: CORS_ALLOWED_ORIGINS
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
