apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accommodation-fe-ti-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 2306214510-fe.hafizmuh.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: accommodation-fe-ti-service
                port:
                  number: 80
